"""fresh schema

Revision ID: 56e048ec9b96
Revises: 
Create Date: 2025-11-23 20:53:22.165220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e048ec9b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programming_language',
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.Column('lang_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('lang_id')
    )
    op.create_table('research_topic',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=60), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wpi_id', sa.String(length=10), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_gpa'), ['gpa'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_wpi_id'), ['wpi_id'], unique=True)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('majorid', sa.Integer(), nullable=False),
    sa.Column('coursenum', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['majorid'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_coursenum'), ['coursenum'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_majorid'), ['majorid'], unique=False)

    op.create_table('research_position',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('min_gpa', sa.Float(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('reference_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('position_id')
    )
    with op.batch_alter_table('research_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_position_min_gpa'), ['min_gpa'], unique=False)

    op.create_table('students_languages_table',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['programming_language.lang_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'lang_id')
    )
    op.create_table('students_majors_table',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'major_id')
    )
    op.create_table('students_topics_table',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['research_topic.topic_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'topic_id')
    )
    op.create_table('application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('statement', sa.String(length=1000), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('faculty_ref_id', sa.Integer(), nullable=True),
    sa.Column('reference_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='status'), nullable=True),
    sa.Column('application_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['faculty_ref_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['research_position.position_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('course_taken',
    sa.Column('course_taken_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=150), nullable=False),
    sa.Column('grade_recieved', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('course_taken_id')
    )
    op.create_table('positions_courses_table',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['research_position.position_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'position_id')
    )
    op.create_table('positions_languages_table',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['programming_language.lang_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['research_position.position_id'], ),
    sa.PrimaryKeyConstraint('position_id', 'lang_id')
    )
    op.create_table('positions_majors_table',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['research_position.position_id'], ),
    sa.PrimaryKeyConstraint('major_id', 'position_id')
    )
    op.create_table('positions_topics_table',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['research_position.position_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['research_topic.topic_id'], ),
    sa.PrimaryKeyConstraint('position_id', 'topic_id')
    )
    op.create_table('reference_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('referee_name', sa.String(length=100), nullable=True),
    sa.Column('referee_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_request')
    op.drop_table('positions_topics_table')
    op.drop_table('positions_majors_table')
    op.drop_table('positions_languages_table')
    op.drop_table('positions_courses_table')
    op.drop_table('course_taken')
    op.drop_table('application')
    op.drop_table('students_topics_table')
    op.drop_table('students_majors_table')
    op.drop_table('students_languages_table')
    with op.batch_alter_table('research_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_position_min_gpa'))

    op.drop_table('research_position')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_majorid'))
        batch_op.drop_index(batch_op.f('ix_course_coursenum'))

    op.drop_table('course')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_wpi_id'))
        batch_op.drop_index(batch_op.f('ix_student_gpa'))

    op.drop_table('student')
    op.drop_table('faculty')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('research_topic')
    op.drop_table('programming_language')
    op.drop_table('major')
    # ### end Alembic commands ###
